### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by asharouthu** [xdsopl/LDPC#3]
While I'm executing testbench.cc I've got two errors in 99 line "aligned_alloc" Is undefined and in 126th line it must have a constant value

**Comment by xdsopl** [comment]
I've just replaced ```aligned_alloc()``` with the aligned ```new``` introduced with C++17 in the work branch.

To fix your second problem, a major rewrite would be necessary, as line 126 is not the only place.
Any volunteers?
