### ISSUE TITLE
Incorrect precision variable in test

### ISSUE THREAD

**Issue by vvsvvsvvs** [xdsopl/LDPC#5]
In the testbench precision is taken from the SNR (sigma_noise), but really, it is required to take it from MER.
Thus, the real performance starts from 0.5 SNR on 50 iterations.

**Comment by xdsopl** [comment]
Yes, there are many problems in there and I haven't touched LDPC codes since playing with Polar codes. Would you like to implement the fixes and create a pull-request?

**Comment by vvsvvsvvs** [comment]
Not just now, but can.

**Comment by xdsopl** [comment]
Take your time
