### ISSUE TITLE
Using with DVBS2

### ISSUE THREAD

**Issue by SimonG4ELI** [xdsopl/LDPC#6]
Hi All,

The problem is with me, _of that I'm sure_. For my own education I'm writing a Windows-based DATV program to use with the QO-100 satellite. I would claim to know what I'm doing most of the time, recently I'm not so sure :) . I have created a simple dialog program which runs this excellent code in a very similar manner to the test bench, this works 100%. I cannot get this the LDPC code to work in 'real life', has anyone here done that?

1. The test bench generates values of 1 and -1 whereas a DVBS2 bitstream is just bits - 0 and 1.
2. I am only decoding one block at a time, later I'll decode up to 32.
3. I *think* my problem may be that I don't understand how to pack a single block as below, lines 160, 161 from testbench.cc. My input is just packed binary data, i.e. a bitstream in a char array.

160: for (int i = 0; i < CODE_LEN; ++i)
161:     reinterpret_cast<code_type *>(simd+i)[n] = code[(j+n)*CODE_LEN+i];

So, how should I present a single block as per line 163?

**163: int count = decode(simd, simd + DATA_LEN, trials, blocks);**

Many thanks in advance, simon@sdr-radio.com

**Comment by xdsopl** [comment]
Have you checked leandvb by @pabr?
https://www.pabr.org/radio/leandvb/leandvb.en.html

It uses a modified version of this project to soft-decode DVB-S2:
https://github.com/pabr/xdsopl-LDPC-pabr

**Comment by SimonG4ELI** [comment]
Thanks, will look at this. I'm sure it's an easy fix.

**Comment by SimonG4ELI** [comment]
Hi, unless I'm mistaken the DVB-S2 decoder from @pabr doesn't perform any LDPC. Still confused! maybe @pabr can help? I think I have his email.

**Comment by xdsopl** [comment]
I was able to successfully demodulate the QO-100 video beacon with a 60 cm dish and a E4000-based RTL-SDR using @pabr's leansdr and the external LDPC soft decoder, so I am pretty sure it does do some LDPC processing.

There is also gr-dvbs2rx by @drmpeg, which uses my code for soft LDCP decoding:
https://github.com/drmpeg/gr-dvbs2rx

It also has my BCH decoder in it.

**Comment by SimonG4ELI** [comment]
Hi,

Many thanks - I'll let you know how I get on, will take a few days.

**Comment by drmpeg** [comment]
Also take a look at https://github.com/igorauad/gr-dvbs2rx

It's a complete DVB-S2 receiver implementation forked from https://github.com/drmpeg/gr-dvbs2rx

**Comment by xdsopl** [comment]
Wow, @igorauad really brought it to the next level. Thanks, Ron.

**Comment by SimonG4ELI** [comment]
> Wow, @igorauad really brought it to the next level. Thanks, Ron.

Yes, very easy to understand.

**Comment by SimonG4ELI** [comment]
Hi All,

Thanks for the help so far, sadly I'm still stuck. My problem must be very simple to solve and due to a misunderstanding of the use of Ahmet's code.

**Question:** In layered_decoder.hh, call:

    int operator()(void* buffer, code_type* code, int trials = 25)

code_type is int8_t. What are the ideal values which correspond to bit values of 0 and 1?

I know my bitstream is 'quite' good as the BBHEADER is OK ~90% of the time even without the LDPC correction, checksum matches and the transport stream values are as expected.

**Comment by xdsopl** [comment]
You need to put log-likelihood ratio (LLR) values in there. Negative values correspond to a '1', positive to a '0' and zero values are 'x', considered erasures (don't know values). The larger the magnitude, the more you trust that value:
https://dictionary.apa.org/log-likelihood-ratio

**Comment by SimonG4ELI** [comment]
> You need to put log-likelihood ratio (LLR) values in there. Negative values correspond to a '1', positive to a '0' and zero values are 'x', considered erasures (don't know values). The larger the magnitude, the more you trust that value: https://dictionary.apa.org/log-likelihood-ratio

Ahmet, thanks for the quick reply. So -128 (0x80) for 1 and 127 (0x7F) for 0. This I'll try.

Just FWIW, I'm using Windows, Visual Studio 2022 C++. I'm writing this project for two main reasons:

1. Thanks for the LLR info, that may clear up some confusion I have.
2. I'm writing a standalone Windows program for DATV on QO-100.

Will reply once I've tried LLR here and in another part of the software.

**Comment by xdsopl** [comment]
If you only work with hard decision bits, you should use -1 and 1 instead of -128 and 127. Otherwise you might run into oversaturation issues. The LDPC decoder works best with soft decision bits, so you should try to get those next. You will be surprised how much more performance you get that way. Good luck.

**Comment by SimonG4ELI** [comment]
> If you only work with hard decision bits, you should use -1 and 1 instead of -128 and 127. Otherwise you might run into oversaturation issues. The LDPC decoder works best with soft decision bits, so you should try to get those next. You will be surprised how much more performance you get that way. Good luck.

Thanks, I'll go back a bit in my code and pass along soft decision bits.

**Comment by xdsopl** [comment]
Ahh, and you probably should also use MinSumAlgorithm instead of the default OffsetMinSumAlgorithm when working with hard decision bits. You should probably disable the SelfCorrectedUpdate but I am curious if that will help you.

**Comment by SimonG4ELI** [comment]
> Ahh, and you probably should also use MinSumAlgorithm instead of the default OffsetMinSumAlgorithm when working with hard decision bits. You should probably disable the SelfCorrectedUpdate but I am curious if that will help you.

Thanks, will give that a go. I tend not to rush at things like this, rather make these options selectable while developing.

**Comment by xdsopl** [comment]
Yes, but the default offset min sum might destroy your hard bits

**Comment by SimonG4ELI** [comment]
> Yes, but the default offset min sum might destroy your hard bits

Hi, will do.

**Comment by SimonG4ELI** [comment]
Yes, now getting full LDPC corrections so I can get on with refining the code. Next to attack is BCH, my own code is being somewhat grumpy.

I'll leave this open for a few days in case I hit problems using LLR / soft values.

**Comment by SimonG4ELI** [comment]
So,

Many thanks for the help, I'm now getting fully corrected frames so I can process the MPEG transport. Once I am displaying the QO-100 beacon and other transmissions I'll revisit this, add LLR etc. to get it more sensitive (if possible).

I've attached a screenshot, just shows a grumpy programmer playing with this code. Aiming for a DATV contact on QO-100 by the end of the year.
![Screenshot-2024-06-19-192302](https://github.com/xdsopl/LDPC/assets/20097654/c36d8e71-256f-4578-ba65-7a513e0a9df7)

**Comment by xdsopl** [comment]
Sounds and looks like you are having fun. That's the spirit!

**Comment by SimonG4ELI** [comment]
So, I'll close this thread for now. With a few decent recordings I made I'm decoding well using hard bits. I may return with soft bit questions in 'some weeks'. Lots of UI stuff first.

Many thanks for the help so far.
