### ISSUE TITLE
Best Sensitivity

### ISSUE THREAD

**Issue by SimonG4ELI** [xdsopl/LDPC#7]
Hi,

Working well with soft symbols. I'm currently using the layered decoder, Self-Corrected Update and OffsetMinSumAlgorithm. What are the recommended settings for low SNR & MER signals irrespective of CPU load?

**Comment by xdsopl** [comment]
You can use the product-sum algorithm and the flooding schedule to get the most robust performance. But in practice, that's not really worth it. The default settings are already good enough and fast.

**Comment by SimonG4ELI** [comment]
Thanks, I'll try SumProductAlgorithm. I have some very marginal recordings I can use for testing.

**Comment by SimonG4ELI** [comment]
Closed, many thanks
